import './globals.scss'
import { Nunito } from 'next/font/google'

import Navbar from './components/Navbar'

const inter = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Tiles App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
