import './globals.scss'
import { Nunito } from 'next/font/google'

import Navbar from './components/Navbar'
import LoginModal from './components/Modal/LoginModal'
import UploadModal from './components/Modal/UploadModal'
import ToasterProvider from './components/providers/ToasterProvider'

import getCurrentUser from './actions/getCurrentUsers'

const inter = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Tiles App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <UploadModal />
        <LoginModal />
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  )
}
